#!/bin/bash

# Autor: Essias Souza <essias.souza@fleetcor.com.br>
# Dezembro de 2023
# Este script tem o objetivo de fazer a instalação sem interação humana.
# Parte do script foi gerado diretamente pelo autoExcept no Linux.

autoStart=/usr/bin/autoStartAbastece.sh
LOG_1='/home/pi/instalador_Axway/Instalacao_manual'$(date +%Y%m)'.log'

sudo cp /suporte/axwayautorecovery/Activator6.1/Activator_6.1_Install_linux-x86-64_BN6.sh /home/pi/
sudo chmod 777 /home/pi/Activator_6.1_Install_linux-x86-64_BN6.sh
sudo cp /home/pi/instalador_Axway/license.xml /home/pi/

# ===== Comentando o EDI do autoStart =====
echo '-- Validando se o EDI está comentado no autoStartAbastece e comentando.' >> $LOG_1

if grep -q "#ediSupport" "$autoStart"; then
    echo '-- ediSupport estava comentado' >> $LOG_1
    if grep -q "#edi" "$autoStart"; then
        echo '-- edi estava comentado' >> $LOG_1
    else
        sudo sed -i '/edi/ s/edi/#edi/g'  $autoStart
        echo '-- edi comentado com sucesso' >> $LOG_1
    fi

else
    if grep -q "#edi" "$autoStart"; then
        echo '-- edi estava comentado' >> $LOG_1
    else
        sudo sed -i '/edi/ s/edi/#edi/g'  $autoStart
        echo '-- edi comentado com sucesso' >> $LOG_1
    fi
fi
sleep 10

# Parando o serviço do EDI se estiver rodando.
sudo echo '-- Parando o serviço do EDI e aguardando 60 segundos.' >> $LOG_1
sudo sh /home/pi/Axway/Activator/Activator force-stop &
wait

# ===== Fazendo a remoção da pasta do Axway =====
sudo echo '-- Removendo todos os arquivos do Axway' >> $LOG_1
sudo rm -Rf /home/pi/Axway

cat <<'EOF' > /home/pi/autoInstall_Activator6.1.sh
#!/usr/bin/expect -f
#
# This Expect script was generated by autoexpect on Mon Dec 11 10:56:31 2023
# Expect and autoexpect were both written by Don Libes, NIST.
#
# Note that autoexpect does not guarantee a working script.  It
# necessarily has to guess about certain things.  Two reasons a script
# might fail are:
#
# 1) timing - A surprising number of programs (rn, ksh, zsh, telnet,
# etc.) and devices discard or ignore keystrokes that arrive "too
# quickly" after prompts.  If you find your new script hanging up at
# one spot, try adding a short sleep just before the previous send.
# Setting "force_conservative" to 1 (see below) makes Expect do this
# automatically - pausing briefly before sending each character.  This
# pacifies every program I know of.  The -c flag makes the script do
# this in the first place.  The -C flag allows you to define a
# character to toggle this mode off and on.
# ===== Nome do script =====

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

#
# 2) differing output - Some programs produce different output each time
# they run.  The "date" command is an obvious example.  Another is
# ftp, if it produces throughput statistics at the end of a file
# transfer.  If this causes a problem, delete these patterns or replace
# them with wildcards.  An alternative is to use the -p flag (for
# "prompt") which makes Expect only look for the last line of output
# (i.e., the prompt).  The -P flag allows you to define a character to
# toggle this mode off and on.
#
# Read the man page for more info.
#
# -Don


set timeout -1
spawn ./Activator_6.1_Install_linux-x86-64_BN6.sh
match_max 100000
expect -exact "Unpacking JRE ...\r
Starting Installer ...\r
\[?7hThis will install Axway Activator on your computer.\r
OK \[o, Enter\], Cancel \[c\]\r
"
send -- "\r"
expect -exact "\r
Click Next to continue, or Cancel to exit Setup.\r
"
send -- "\r"
expect -exact "\r
Please read the following License Agreement. You must accept the terms of\r
this agreement before continuing with the installation.\r
\r
LICENSE, SUPPORT, AND SERVICES AGREEMENT\r
General Conditions\r
\r
This License Support and Services Agreement is an agreement between the\r
entity receiving the accompanying product(s), documentation or services\r
(\"Customer\") and Axway Inc. (or, based on where Customer acquired the\r
licenses, one of its affiliates) (\"Axway\"). This Agreement, including\r
any and all Order Forms and SOWs (as defined below) (collectively, this\r
\"Agreement\"), governs the products(s), documentation and services that\r
accompany this Agreement.\r
\r
Click-through Agreement. BY INSTALLING, COPYING OR USING THE PRODUCT(S) OR\r
DOCUMENTATION ACCOMPANYING THIS AGREEMENT AND/OR CLICKING ON THE \"I\r
ACCEPT\" BUTTON OF ANY ELECTRONIC VERSION OF THIS AGREEMENT, YOU (AS THE\r
INDIVIDUAL SIGNING OR CLICKING ON THIS AGREEMENT) AS THE CUSTOMER\r
REPRESENT AND WARRANT THAT YOU ARE DULY AUTHORIZED ON BEHALF OF CUSTOMER\r
TO ENTER INTO THIS AGREEMENT ON BEHALF OF CUSTOMER, AND CUSTOMER CONSENTS\r
TO AND AGREES TO BE BOUND BY THE TERMS AND CONDITIONS OF THIS AGREEMENT.\r
IF CUSTOMER DOES NOT AGREE TO ALL OF THE TERMS AND CONDITIONS OF THIS\r
AGREEMENT, CLICK THE \"I DO NOT ACCEPT\" BUTTON. IF THIS IS AN ELECTRONIC\r
VERSION OF THIS AGREEMENT, DO NOT INSTALL, COPY OR USE THE PRODUCT(S) OR\r
DOCUMENTATION, AND IMMEDIATELY RETURN THE PRODUCT(S) AND DOCUMENTATION TO\r
AXWAY.\r
\[Enter\]\r
\r
ARTICLE 1 - DEFINITIONS AND INTERPRETATION 1.1. In this Agreement and any\r
Schedules, Order Forms or Statements of Work (\"SOWs\"), the following terms\r
are defined as follows, and additional definitions applicable to the Order\r
Forms are included in Attachment A:\r
\"Additional Services\" means the Services described in Article 7 as\r
contained in any Order Forms or SOWs;\r
\"Agreement\" means these General Conditions and the Software/Services Order\r
Form (or Specific Conditions) and Schedules (together, the \"Order Form\");\r
\"Business Partner\" or \"Trading Partner\" means any external computer\r
interoperating with a Licensed Component through one or more protocols, one\r
or more networks, or one or more adapters;\r
\"Defect\" means a reproducible error or defect in the Product that prevents\r
it from operating materially in accordance with its Documentation;\r
\"Delivery\" means delivery of license keys which unlock the Licensed\r
Component, enabling electronic delivery of the Licensed Component for\r
download, or shipment of one or more CD ROMs or DVDs which contain the\r
Licensed Component, or shipment of the Hardware Product;\r
\"Documentation\" means the documents delivered with\r
the Product which contains Axway's published specifications and user guide\r
of the Product;\r
\"Effective Date\" for an Order Form means the date when Customer executes an\r
Order Form unless specified otherwise in an Order Form;\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
\"Hardware Product\" means any hardware appliance or other item of equipment\r
that is delivered to Customer;\r
\"Licensed Component\" means the computer program described in the Order\r
Form, as well as:\r
(i) the Documentation, in either machine-readable or printed form; and\r
(ii) all entire or partial authorized copies of such items made by\r
Customer; and\r
(iii) any software release provided by Axway to Customer (provided that\r
Customer is still a subscriber to Support Services);\r
\"Operating Environment\" means any operating system based environment\r
hosting the running of a Licensed Component, defined by its resources:\r
Computer, its number of CPUs, its number of Cores per CPUs, its number of\r
Partitions, the type of its Partitions and the number of CPUs per\r
Partitions;\r
\"Parties\" means Axway and the party identified as Customer in the Order\r
Form;\r
\"Product\" means Hardware Product(s) and Licensed Component(s);\r
\"Site\" means the physical location of the Operating Environment, such\r
address as is provided in the Order Form; \"Support Services\" means annual\r
Product support provided under Axway's policies for the level of Support\r
Services ordered in the Order Form; \"Third Party Software\" means any third\r
party program or software included as an integral part of the Product and\r
delivered with the Product; such program or software is solely for use as\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
embedded with the Product;\r
\"Use\" means the installation, loading, utilization, storage or display of\r
the Product by Customer within the constraints in the Order Form;\r
1.2. Headings are used in this Agreement for ease of reference only and\r
shall not affect interpretation. References in this Agreement to Articles\r
or Sections are references to the Articles or Sections of the General\r
Conditions unless inconsistent with the context.\r
1.3. The words \"include\", \"includes\", \"including\" and \"included\" will be\r
construed without limitation unless inconsistent with the context.\r
\r
ARTICLE 2 - CONTRACT DOCUMENTS\r
2.1. This Agreement consists of these General Conditions, and any Order\r
Form(s) or Specific Conditions, which prevail over these General Conditions\r
to the extent of any conflict.\r
2.2. This Agreement forms the entire agreement between the Parties relating\r
to this subject matter, replaces and supersedes any previous proposals,\r
correspondence and understandings, whether written or oral; including any\r
Customer terms and conditions, which shall not apply.\r
2.3. This Agreement may not be altered, modified, amended, changed,\r
rescinded or discharged in whole or in part, except by written agreement\r
signed by both Customer and Axway.\r
2.4. Nothing contained in any document or purchase order submitted by\r
Customer shall in any way modify or add to the terms of this Agreement.\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
\r
ARTICLE 3 - TERM\r
3.1. This Agreement shall remain in effect unless terminated in accordance\r
with Article 17. The right of Use is granted from the Effective Date, or if\r
none stated, upon Delivery by Axway.\r
3.2. If purchased by Customer, Support Services shall commence on the\r
Effective Date and shall continue for an initial period of one year\r
(\"Initial Support Term\") except as otherwise set forth in the Order Form.\r
Upon expiration of the Initial Support Term, the Support Services shall be\r
automatically renewed for one-year periods, with payments required prior to\r
the start of the new support term, unless and until terminated in\r
accordance with Article 17.\r
3.3 The terms of this Section 3.3 apply if Customer is obtaining an\r
evaluation license. Subject to the terms of this Agreement, Axway grants\r
to Customer (i) a non-exclusive, nontransferable license, without right of\r
sublicense, to install and Use the evaluation version of the Licensed\r
Component, in object code form and/or (ii) the right to Use the Hardware\r
Product for evaluation and trial purposes only. The term of this license\r
begins upon delivery or download and ends 30 days thereafter, or extends\r
for such longer period as Axway shall have agreed to in writing (the\r
\"Evaluation Period\"). When the Evaluation Period expires Customer must\r
stop Using the Licensed Component, and return any Product to Axway. Axway\r
disclaims all warranties during this Evaluation Period and Customer waives\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
all claims against Axway related to this Evaluation Period.\r
\r
ARTICLE 4 - USE OF THE PRODUCT\r
4.1. As of the Effective Date of this Agreement, Axway grants to Customer,\r
subject to the terms and conditions of this Agreement, a non-exclusive, non-\r
assignable and non-transferable right to Use the Licensed Component for\r
Customer's own internal business purposes only. Any delay in any payment of\r
the fees related to this Agreement as set forth in Article 8 thirty (30)\r
days beyond the payment date will automatically suspend the right to Use\r
the Licensed Component for Customer, upon written notice by Axway. The\r
Product, including portions and information or materials thereof, may not\r
be used for any purpose that would be a violation of this Agreement. All\r
rights not addressed herein are specifically reserved by Axway. Customer\r
shall not Use the Product to provide services to third parties, including\r
ASP, facilities management, outsourcing, unless expressly provided for in\r
an Order Form.\r
4.2. If Customer has purchased a license for Products which are used by\r
Customer to distribute to any third party Trading Partner that has a\r
business need to securely transfer files to or from Customer, then the\r
sublicense such Trading Partner has conveys the right to Use the Product\r
for the purpose of transferring files to and from Customer in the\r
furtherance of Customer's internal business purposes only.\r
4.3. If Customer wishes to permanently transfer the Licensed Component to a\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
new Operating Environment, the Order Form associated with this Agreement\r
will have to be updated accordingly. Once the transfer has been made to the\r
new authorized Operating Environment, Customer shall erase the Licensed\r
Component from the former Operating Environment, within the time frame\r
allowed in the Order Form or, if none stated, then sixty days.\r
4.4. Customer has the right to make one back-up copy of the Licensed\r
Component for archival purpose only. Any other copies, reproductions and\r
summaries of the Licensed Component or Documentation are prohibited.\r
\r
ARTICLE 5 - DELIVERY AND WARRANTY\r
5.1. Axway shall provide Customer with the Licensed Component in object\r
code form and with the Documentation. Full title to the Hardware Product\r
passes to Customer upon Delivery. Products are delivered Free On Board\r
(FOB) shipping point with freight and insurance prepaid.\r
5.2. The Use of certain Licensed Components will require a key. The key\r
will be generated by Axway based on computer- dependent Customer\r
information. Customer agrees to provide the necessary information as\r
required to generate and activate the key.\r
5.3. Axway represents and warrants that, for a period of 90 days from\r
Delivery (\"Warranty Period\"), the Product will conform to and perform in\r
accordance with the Documentation. Unless certified by Axway, Axway does\r
not warrant that the Product will operate in combination with other\r
software selected by Customer, or that the Product will operate\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
uninterrupted or free of non- material errors. Axway will use commercially\r
reasonable efforts to modify, repair or replace the Product, at no\r
additional charge, to correct any Defect, provided that Customer reports\r
the Defect to Axway during the Warranty Period. Axway further warrants\r
that the Product as provided by Axway will not contain any malicious code,\r
program, or internal component (e.g., computer worm) and will have been\r
screened using customary procedures in the industry for viruses. THE\r
REMEDIES DESCRIBED IN THIS ARTICLE 5 SHALL BE THE SOLE AND EXCLUSIVE\r
REMEDIES FOR DEFECTS CONTAINED IN AND FOR THE PERFORMANCE OF THE PRODUCT.\r
5.4. The limited warranties in Section 5.3 are conditioned upon Customer's\r
Use of the Product in accordance with the terms of the Documentation, and\r
shall not apply to the extent that an error occurs because of and would not\r
have occurred but for: (i) modifications made to the Product by a party\r
other than Axway; (ii) Customer's failure to implement enhancements\r
provided by Axway; or (iii) Use of the Product in connection with any\r
operating system, computer equipment or device which does not meet the\r
minimum requirements set forth in the Documentation.\r
5.5. EXCEPT FOR THE\r
EXPRESS WARRANTIES SET FORTH IN THIS ARTICLE 5,TO THE EXTENT PERMITTED BY\r
APPLICABLE LAW, AXWAY DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED,\r
INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY,\r
TITLE AND FITNESS FOR A PARTICULAR USE OR PURPOSE.\r
\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
ARTICLE 6 - SUPPORT SERVICES\r
6.1. Upon payment of the applicable fees, Axway will provide technical\r
Support Services, at the level specified on the Order Form or other\r
applicable ordering documentation.\r
6.2. Axway is under no obligation to provide Support Services (i) if there\r
has been a modification or attempted modification of the Product (other\r
than modifications made by Axway and delivered as part of the Product) or\r
the Product has been improperly installed by Customer or operated or used\r
other than in accordance with this Agreement and the Documentation; or (ii)\r
if Customer has refused, delayed or otherwise failed to implement a release\r
or other modification that Axway has provided or recommended.\r
\r
ARTICLE 7 - ADDITIONAL SERVICES\r
7.1. In accordance with its expertise and availability, Axway will, if\r
ordered by Customer, provide services that may include installation,\r
implementation, technical and training assistance services for the Product,\r
or subscription-based or hosting services (each considered individually,\r
\"Additional Services\") to Customer at the rates set forth in the Order Form\r
or, if no rates are set forth, the rates in effect at the time that such\r
Services are provided.\r
7.2. Except for Retained Works (defined below), all right and title to\r
professional services deliverables shall belong to Customer. Axway will be\r
the owner of any Retained Works, which are defined to include: (i) any pre-\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
existing materials, including any of Axway's preexisting software code,\r
proprietary software tools, or training materials incorporated into the\r
deliverables; (ii) any customized modifications to the Licensed Component\r
unless an applicable work order, SOW or other such similar document\r
expressly provides that such modifications are assigned to Customer; and\r
(iii) any third party programs which are integrated with or incorporated\r
into the deliverables. For any Retained Works incorporated into a\r
deliverable, Axway grants Customer a nonexclusive, worldwide, royalty-free\r
license to use such Retained Works to the same extent that Customer is\r
licensed to use any related Licensed Component.\r
\r
ARTICLE 8 - PAYMENT TERMS AND CONDITIONS\r
8.1. The fees for the Products and Support Services are listed in the Order\r
Form. In addition to the fees listed in the Order Form, Customer shall be\r
responsible for all personal property, sales, use, value-added, withholding\r
and similar taxes (other than taxes on Axway's net income) arising from the\r
transactions described in this Agreement. Where Customer's Use of the\r
Software or receipt of Services is exempt from sales or other taxes,\r
Customer shall provide Axway with the appropriate exemption certificate.\r
All amounts payable under this Agreement shall be paid net 30 days from the\r
invoice date, unless stated otherwise in an Order Form.\r
8.2. The Product fees are fixed and not subject to revision. It shall be\r
invoiced in full on the Effective Date, unless stated otherwise in an Order\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
Form.\r
8.3. Support Services fees shall be invoiced on the Effective Date and are\r
due net 30 unless otherwise stated in an Order Form.\r
8.4. Fees for professional services shall be invoiced at the end of the\r
month in which they are provided. Travel and accommodation expenses\r
incurred to provide training, technical assistance, support and services\r
shall be invoiced to Customer based on the actual and reasonable costs\r
incurred by Axway. Supporting documents will be provided upon reasonable\r
request.\r
8.5. Fees or other amounts remaining unpaid for thirty (30) days following\r
the date of invoice shall be considered overdue and shall remain payable by\r
Customer together with interest for late payment from the date payable at\r
the rate of 1% per month. In addition to the above provision for late\r
payment, Axway reserves the right to suspend performance of any Additional\r
Services (which includes hosting services, as applicable).\r
\r
ARTICLE 9 - CUSTOMER RESPONSIBILITIES\r
9.1. Unless the hosted option is selected, Customer shall be responsible\r
for operating the Product and shall:\r
-	ensure that the hardware, base program, network and operating system\r
configuration are suitable,\r
-	develop the operating measures, control procedures and security\r
measures required for data backup and replacement in the event of\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
interruption in Product operation,\r
9.2. Customer is also responsible for:\r
-	protecting its own recorded data, and\r
- the results obtained and any direct or indirect consequences thereof,\r
- make qualified personnel available to resolve any problems, and\r
- appoint one of its employees to serve as the primary point of contact\r
with Axway for any technical issues.\r
9.3. Customer shall take all measures required to protect Axway's\r
intellectual property rights in the Product and Documentation, including in\r
particular retaining any reference to Axway's copyright notice(s) and any\r
other legend on any authorized copy in accordance with Axway's\r
instructions. In the event any third party attempts to attach or seize the\r
Product or challenge Axway's intellectual property rights in any other\r
manner, Customer must immediately notify Axway, contest the attachment and\r
take all steps required to make the intellectual property rights in\r
question known, subject always to Article 10 below.\r
\r
ARTICLE 10 - INTELLECTUAL PROPERTY\r
10.1. Only a right to Use the Licensed Component is granted to Customer;\r
any extension of the right granted shall be subject to Axway's prior\r
written consent. The parties acknowledge and agree that Customer has only\r
Use rights with respect to the Licensed Component, but Customer owns the\r
Hardware Product. Axway retains title in and to the Licensed Component,\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
including any portion thereof and information, materials or copy made from\r
it or any part of it and copyright in the Licensed Component.\r
10.2. If Customer wishes to make the Product interoperable with other\r
programs, other than as envisaged in the Documentation, the parties will\r
work together to create an interoperability plan that does not violate this\r
Article.\r
10.3. Except as otherwise provided for in this Agreement or permitted under\r
applicable law, Customer will not, directly or through any person or\r
entity, in any form or manner (i) copy, sublicense, lease, assign,\r
distribute, reproduce, incorporate, use or allow access to the Product or\r
modify, prepare derivative works from the Licensed Component except as\r
explicitly permitted under this Agreement or (ii) decrypt, extract,\r
decompile or otherwise reverse engineer the Licensed Component, or\r
otherwise disassemble, derive or attempt to derive the source code of, or\r
any processes, methods, specifications, protocols, algorithms, interfaces,\r
data structures, or other information embodied or used in, the Product. The\r
restrictions of this Article 10 shall survive the termination of the\r
Agreement. If Customer has purchased licenses for a Trading Partner,\r
Customer shall ensure each Trading Partner is bound to provisions at least\r
as protective of Axway as Articles 4, 10, 12, 14 and 15. Customer shall\r
promptly notify Axway of any unauthorized use, disclosure, reproduction, or\r
distribution of any Product, which comes to Customer's attention, or which\r
Customer reasonably suspects. Customer may Use any Third Party Software\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
products or modules supplied by Axway solely with the Licensed\r
Component.\r
10.4. If, in the performance of any Additional Services hereunder, Axway is\r
required to use any Customer supplied programs, Customer hereby warrants\r
that it has obtained any necessary authorizations and licenses required to\r
allow Axway to access and use such program as necessary for performance of\r
the Services. Customer shall provide any associated supporting\r
documentation to Axway promptly upon request.\r
\r
ARTICLE 11 - INDEMNIFICATION\r
11.1. Axway agrees to defend, settle and indemnify Customer from and\r
against any amounts payable under judgment, court order or settlement\r
brought by any unaffiliated third party against Customer to the extent that\r
such action results from actual or alleged infringement by any Product of\r
any third party copyright, trade secret or patent existing or issued as of\r
the date that Axway initially Delivered the applicable version of such\r
Product to Customer. In connection with any allegation of infringement of\r
any third party rights, Customer shall (and it shall be a condition of\r
reliance upon the indemnity for Customer to):\r
- immediately notify Axway in writing of the allegation; and\r
-	allow Axway sole control of the defense and any related settlement\r
negotiations; and\r
-	cooperate in good faith in the said defense and comply with all of\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
Axway's reasonable requests (at Axway's expense) in defending or settling\r
the claim.\r
11.2. Should Customer's use of the Product be determined to have infringed\r
any third party rights, or if in Axway's judgment, such use is likely to be\r
infringing, Axway shall endeavor at its option do one of the following, at\r
its own expense:\r
-	procure for Customer the right to continue owning or using the Product,\r
as applicable,\r
-	replace or modify the Product to make its Use non-infringing while\r
yielding substantially equivalent functionality.\r
If and only if the previous options are not, in Axway's reasonable\r
judgment, commercially reasonable, then Axway may terminate this Agreement\r
as it applies to the specific Product and the corresponding rights of Use.\r
Customer agrees to destroy or return the affected Product to Axway on its\r
written request and Axway will then return the Product license fees to\r
Customer as prorated over a five year term commencing on the date of\r
Delivery of the applicable Product by Axway. The obligations of Axway in\r
this Article 11 will not apply to the extent that the infringement or claim\r
thereof is based on (i) Use of the Product other than in accordance with\r
this Agreement, or (ii) modifications or additions to the Product by\r
Customer personnel (other than modifications at Axway's direction) or (iii)\r
use of other than the most recent version of any Product if and from the\r
time Axway informs Customer in writing that infringement or\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
misappropriation may be avoided by use of the most recent version of such\r
Product. THIS ARTICLE 11 SETS FORTH THE FULL SCOPE OF AXWAY'S LIABILITY AND\r
CUSTOMER'S EXCLUSIVE REMEDY, TO THE EXTENT PERMITTED BY LAW, FOR ANY ACTUAL\r
OR ALLEGED INFRINGEMENT OF THIRD PARTY RIGHTS IN CONNECTION WITH THE\r
PRODUCT.\r
\r
ARTICLE 12 - LIABILITY\r
12.1. EXCEPT FOR AXWAY'S OBLIGATIONS WITH RESPECT TO INDEMNIFICATION OR\r
CONFIDENTIALITY, AXWAY IS NOT LIABLE FOR ANY SPECIAL, INDIRECT, EXEMPLARY,\r
INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING,\r
WITHOUT LIMITATION, DAMAGES FOR LOSS OF GOODWILL, WORK STOPPAGE, LOST\r
PROFITS, LOST DATA OR COMPUTER HARDWARE OR SOFTWARE DAMAGE, FAILURE OR\r
MALFUNCTION, WHETHER OR NOT AXWAY HAS BEEN ADVISED OF THE POSSIBILITY OF\r
SUCH DAMAGES; EXCEPT FOR AXWAY'S OBLIGATIONS WITH RESPECT TO\r
INDEMNIFICATION OR CONFIDENTIALITY, AXWAY'S LIABILITY HEREUNDER SHALL NOT\r
EXCEED THE TOTAL AMOUNT OF LICENSE AND SERVICES FEES INVOICED UNDER THIS\r
AGREEMENT FOR THE SOFTWARE GIVING RISE TO SUCH LIABILITY DURING THE\r
CALENDAR YEAR IN WHICH THE CLAIM AROSE. THE FOREGOING LIMITATIONS OF\r
LIABILITY AND DISCLAIMERS OF DAMAGES APPLY REGARDLESS OF THE FORM IN WHICH\r
AN ACTION (LEGAL, EQUITABLE OR OTHERWISE) MAY BE BROUGHT, WHETHER IN\r
CONTRACT, TORT, OR OTHERWISE. THE LIMITATIONS OF LIABILITIES, DISCLAIMERS\r
OF WARRANTIES, EXCLUSIVITY OF REMEDIES AND OTHER LIMITATIONS SET FORTH\r
HEREIN ARE AN ESSENTIAL ELEMENT OF THE BARGAIN BETWEEN THE PARTIES (WITHOUT\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
WHICH THE TRANSACTIONS CONTEMPLATED BY THIS AGREEMENT WOULD NOT OCCUR) AND\r
WILL APPLY EVEN IF A REMEDY FAILS IN ITS ESSENTIAL PURPOSE.\r
12.2. This Agreement is enforceable by the Parties to it and by their\r
permitted assignees. A person who is not a party to this Agreement shall\r
have no right to enforce or rely on any of the terms of this Agreement. The\r
terms of this Article 12 shall survive termination of this Agreement.\r
\r
ARTICLE 13 - ADVERTISING\r
The Customer must include Axway's name any time it refers to the Product in\r
writing. The Customer hereby authorizes Axway to include its name in a\r
customer list.\r
\r
ARTICLE 14 - ADMINISTRATIVE REQUIREMENTS\r
The Customer is responsible for obtaining any required legal authorizations\r
arising out of Customer's particular use of the Products and is responsible\r
for its compliance with applicable data protection legislation.\r
\r
ARTICLE 15 - CONFIDENTIALITY\r
15.1. Each Party recognizes that under this Agreement either Party may have\r
access to or otherwise receive trade secrets and confidential or\r
proprietary information of the other, including information concerning\r
products, including but not limited to the names of Customer's clients,\r
financial or contractual arrangements. All such information shall\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
constitute \"Confidential Information\". The Products, including any\r
Documentations or portions thereof and information, material or copy\r
derived there from, is proprietary and confidential to Axway. Each Party\r
agrees not to use, other than for the purposes for which it was disclosed\r
or divulged the other party's Confidential Information and to limit\r
disclosure of same to those of its employees and independent contractors\r
who have a need to know the same and to use all reasonable endeavors to\r
prevent its disclosure to or access by any third party without the prior\r
written consent of the disclosing party.\r
15.2. Confidential Information does not include information that: (i) is or\r
becomes a part of the public domain through no act or omission of the\r
receiving Party; (ii) was in the receiving Party's lawful possession prior\r
to the disclosure and had not been obtained by the receiving Party either\r
directly or indirectly from the disclosing Party; (iii) is lawfully\r
disclosed to the receiving Party by a third party without restriction on\r
disclosure; (iv) is independently developed by the receiving Party without\r
reference to the disclosing Party's Confidential Information; or (v) is\r
required to be disclosed by any court of competent jurisdiction or by a\r
governmental or regulatory authority or where there is a legal right, duty\r
or requirement to disclose. In such event, the receiving Party will (and\r
without breaching any legal or regulatory requirement) where reasonably\r
practicable give the disclosing Party prompt notice in writing of the\r
requirement to disclose.\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
15.3. The rights and obligations of the Parties under this Article 15 shall\r
continue for three years following expiration or termination of this\r
Agreement.\r
\r
ARTICLE 16 - NON-SOLICITATION\r
16.1. For the duration of this Agreement and for the period of 12 months\r
following its termination or expiration, neither Party shall, without the\r
prior written consent of the other Party, actively endeavor to solicit or\r
entice away any person employed or engaged by the other Party in the\r
performance or administration of this Agreement.\r
16.2. If a Party breaches the foregoing obligation, the breaching party\r
shall pay to the other Party twelve times the prior monthly base salary of\r
the relevant person, such sum being deemed by both Parties to be fair\r
compensation for the loss suffered as a result of the breach.\r
16.3. The provisions of Section 16.2 shall not apply to any individual who\r
can be proven to have responded to a bona fide published recruitment\r
advertisement where the recruited person is not recruited to work for or\r
with a party's personnel or department involved in this Agreement. Nothing\r
in this Article 16 is intended to restrict the right of any individual to\r
seek employment with whomsoever they wish, but is intended to provide for\r
due compensation where such a situation occurs as a result of entering into\r
this Agreement recognizing that loss of experienced personnel can have a\r
serious effect upon any employer.\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
\r
ARTICLE 17 - TERMINATION\r
17.1. This Agreement may be terminated by either Party immediately upon\r
written notice if the other Party is in material or continuing breach of\r
any of its obligations under this Agreement and fails to remedy that breach\r
(if capable of remedy) within thirty (30) days after receiving written\r
notice of such breach.\r
17.2. Either Party may terminate this Agreement forthwith on giving written\r
notice to the other Party if such Party has had a receiver or\r
administrative receiver appointed over the whole or any part of its\r
undertaking or assets or passes a resolution for winding up, or a court of\r
competent jurisdiction makes an order to that effect or if the other Party\r
enters into any voluntary arrangement with its creditors or becomes subject\r
to a bankruptcy administration order or ceases to carry on business.\r
17.3. Upon termination of the Agreement Customer must, depending on the\r
method of Product delivery, either: (i) return the Licensed Component and\r
the Documentation to Axway and destroy or return any copies of the Licensed\r
Component that it may have made within fifteen days from the termination\r
date or (ii) remove all copies of the Licensed Component and certify in\r
writing that all copies have been removed and destroyed.\r
17.4. After the Initial Support Term or any of the annual renewal of\r
Support Services terms, either Party may terminate the Support Services on\r
six months' prior written notice.\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
\r
ARTICLE 18 - WAIVER\r
The fact that either Party fails to take action after a breach by the other\r
Party of any of its obligations arising hereunder shall not be construed or\r
operate as a waiver of the obligation in question or of any later breach.\r
\r
ARTICLE 19 - SEVERABILITY\r
If any of the provisions of this Agreement, or any part thereof, is judged\r
to be illegal or unenforceable, the remaining provisions will continue in\r
full force and effect for the remainder of this Agreement and shall not be\r
prejudiced, unless the substantive purpose of this Agreement is thereby\r
frustrated, in which case either Party may terminate this Agreement\r
forthwith on written notice.\r
\r
ARTICLE 20 - ASSIGNMENT\r
This Agreement and the license granted hereunder may not be assigned or\r
transferred in whole or in part by Customer without Axway's prior written\r
consent. Axway may assign and transfer its complete rights and obligations\r
under this Agreement, without the consent of Customer, to any corporation\r
that is a wholly owned subsidiary or parent or sister corporation of Axway.\r
\r
ARTICLE 21 - AUDIT\r
Axway hereby reserves the right to conduct an on-site audit of Customer to\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
verify compliance with the Licensed Component license granted herein by\r
providing at least three (3) days prior written notice. Customer consents\r
to audit compliance software being run on Customer systems. The Customer\r
hereby agrees to cooperate with the audit in good faith, to grant Axway\r
access to all relevant information and to provide copies of relevant\r
information on request. In addition, Customer agrees, upon request by\r
Axway from time to time, to provide Axway with a written report, certified\r
by an officer, stating the physical Site(s) and computer systems with\r
respect to which Customer is using the Licensed Component.\r
\r
ARTICLE 22 - UNITED STATES GOVERNMENT END USERS\r
As defined in Federal Acquisition Regulations (\"FAR\") Section 2.101,\r
Department of Defense Federal Acquisition Regulations (\"DFARs\") Section\r
252.227-7014(a)(1) and DFAR Section 252.227-7014(a)(5), the computer\r
programs included in or with the Products and the Documentation are\r
\"commercial items,\" \"commercial computer software\" and \"commercial computer\r
software documentation,\" as applicable. Consistent with FAR Section 12.212\r
and DFAR Section 227.7202 and any successor sections, any use,\r
modification, reproduction, release, performance, display or disclosure of\r
such computer programs and Documentation by the United States Government\r
shall be governed solely by the terms of this Agreement.\r
\r
ARTICLE 23 - EXPORT\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
Customer shall not export, ship, transmit or re-export the Products or\r
Documentation in violation of any applicable law or regulation.\r
\r
ARTICLE 24 - THIRD PARTY SOFTWARE\r
Certain Third Party Software may be provided with the Licensed Component(s)\r
that is subject to the accompanying license(s), if any, of its respective\r
owner(s). To the extent portions of the Software are distributed under and\r
subject to open source licenses obligating Axway to make the source code\r
for such portions publicly available (such as the GNU General Public\r
License (\"GPL\") or the GNU Library General Public License (\"LGPL\")), Axway\r
will make such source code portions (including Axway modifications, as\r
appropriate) available upon request for a period of up to three years from\r
the date of distribution. Such request can be made in writing to Axway\r
Inc., 6811 E. Mayo Blvd., Suite 400, Phoenix, Arizona 85054, ATTN: Legal\r
Department. Customer may obtain a copy of the GPL at\r
http://www.gnu.org/licenses/gpl.html, and a copy of the LGPL at\r
http://www.gnu.org/licenses/lgpl.html.\r
\r
ARTICLE 25 - NOTICES\r
All notices, demands, consents, approvals and other communications shall be\r
sufficient if in writing and sent by facsimile transmission (with a hard\r
copy mailed on the same date) or registered or certified mail, return\r
receipt requested, postage prepaid, or overnight courier service to the\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
other party at its address set out in the Order Form or to such other\r
superseding notice address that it has subsequently provided to other Party\r
in writing. Each such notice shall be deemed to have been served: in the\r
case of by hand and special delivery, when actually received; or if posted\r
by recorded delivery shall be deemed to have been accepted on the expiry of\r
forty eight hours after posting and on proving posting it shall be\r
sufficient to produce a copy of the notice properly addressed with the\r
relevant post office receipt for its dispatch by recorded delivery.\r
\r
ARTICLE 26 - GOVERNING LAW and DISPUTES\r
26.1. This Agreement will be governed by and interpreted in accordance with\r
the laws of Arizona. Should any dispute arise, the Parties will use all\r
reasonable efforts to attempt to resolve the dispute in good faith by\r
senior level negotiations. The dispute shall be referred by a written\r
request to an officer of each Party who has authority to resolve the\r
dispute and who is not directly involved with the subject matter of this\r
Agreement who shall meet within 15 days from the dispatch of the written\r
request in order to attempt to resolve the dispute.\r
26.2. If the dispute is not resolved through negotiation, both Parties\r
agree that the Courts of Arizona will have exclusive jurisdiction in\r
connection with the resolution of the dispute. The United Nations\r
Convention on the International Sale of Goods shall not apply to this\r
Agreement.\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
\r
\r
\r
ATTACHMENT A ADDITIONAL DEFINITIONS\r
\r
To the extent used in the Order Forms pursuant to this Agreement, the\r
following definitions have the following meanings:\r
\r
\"Active (Production) License\" means a license for Use of the Product in a\r
production environment. An Active/Active configuration refers to a shared\r
cluster configuration whereby applications and data are simultaneously\r
available to all server Instances in the cluster. Consequently,\r
Active/Active clusters support high availability ;\r
\"Computer\" means one or a group of physical hardware machines processing\r
data and hosting the running of one or more operating systems as defined in\r
the Order Form;\r
\"Core\" means the main part of CPU that interprets the instructions and\r
performs the binary calculations. Every CPU has at least one Core, but can\r
be composed of several Cores;\r
\"CPU\" (Central Processing Unit) means a functional unit in a computer that\r
interprets and executes instructions. A CPU may contain multiple Cores with\r
a Computer system or server. If the right of Use is based on CPUs and if\r
the Licensed Component is used on a single computer with multiple CPUs, the\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
CPU license must correspond with the number of respective Cores contained\r
within such Computer. For example, a server that uses one dual-Core CPU\r
requires two CPU licenses, and a server that uses four dual-Core CPUs\r
requires eight CPU licenses;\r
\"Instance\" means a single occurrence of a Licensed Component. For\r
clarification, if Customer has purchased only one Active Production\r
Instance, Customer may run a single occurrence of the Licensed Component in\r
RAM (Random Access Memory); \"Named User\" means a physical person\r
susceptible to establish a session with the Licensed Component;\r
\"Node\" means a running instance of a Axway program, i.e. a JVM (Java\r
Virtual Machine) running an Axway application;\r
\"Partition\" means a reserved part of the resources of an Operating\r
Environment that is set aside for a specific purpose; Such as:\r
- \"Capped-Partition\" means the Sub-Capacity Partition using a determined\r
maximum subset of the resources of an Operating Environment.\r
- \"Floating Partition\" means the Sub-Capacity Partition using a\r
dynamically allocated subset of the resources of an Operating\r
Environment. The maximum potential of resources used by a Sub- Capacity\r
Partition equals the overall resources of the Operating Environment;\r
- \"Full-Capacity Partition\" means a Partition using all the resources of\r
an Operating Environment. There can only be one \"Full- Capacity\r
Partition\" per Operating Environment. If there is another partition,\r
then both Partitions are \"Sub-Capacity Partitions\";\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
- \"Sub- Capacity Partition\" means a partition using a subset of the\r
resources of an Operating Environment;\r
\"Passive (Non-Production) License\" refers to a cluster fail over or\r
disaster recovery software architecture. The passive software doesn't\r
execute unless the licensed production copy of the Licensed Component\r
fails. Where Customer is not able to use its licensed production copy of\r
the Licensed Component in the event of fail over, the Passive license will\r
start executing after a service interruption. A Passive License may also\r
include those for test, development, archiving or quality control/quality\r
assurance;\r
\"User\" means, unless otherwise stated in the applicable Order: (a) with\r
respect to all Products other than Products that are part of Axway's\r
Validation Authority or SecureTransport product suites, any person who is\r
assigned login or Use rights or credentials by Customer to access the\r
applicable Product, whether directly, through another application or\r
otherwise; (b) with respect to any Product included in Axway's\r
SecureTransport product suite, any person or system who is assigned login\r
or Use rights or credentials by Customer to access the applicable Product,\r
whether directly, through another application or otherwise; and (c) with\r
respect to any Product included in Axway's Validation Authority product\r
suite, any Validation Authority User.\r
\"Validation Authority User\" means any Human User, Group User or Non-Human\r
User.\r
\[Enter\]\r
"
send -- "\r"
expect -exact "\r
- \"Human User\" means, with respect to the applicable Product included in\r
Axway's Validation Authority product line, any human who has one or more\r
associated digital certificates associated with such human that: (i)\r
uniquely identify such human; and (ii) are contained in a database or\r
other repository that can be queried through Customer's implementation\r
of such Product.\r
- \"Group User\" means, with respect to the applicable Product included in\r
Axway's Validation Authority product line, any group of humans that has\r
one or more associated digital certificates that: (i) uniquely identify\r
such group; and (ii) are contained in a database or other repository\r
that can be queried through Customer's implementation of such Product.\r
- \"Non-Human User\" means, with respect to the applicable Product\r
included in Axway's Validation Authority product line, anything other\r
than a Human User or Group User (such as a device) (\"Non-Human\") that\r
has one or more associated digital certificates that: (i) uniquely\r
identify such Non-Human; and (ii) are contained in a database or other\r
repository that can be queried through Customer's implementation of such\r
Product.\r
\r
I accept the agreement\r
Yes \[1\], No \[2\]\r
"
send -- "1\r"
expect -exact "1\r
Select the folder where you would like Axway Activator to be installed, then\r
click Next.\r
Where should Axway Activator be installed?\r
\[/root/Axway\]\r
"
send -- "/home/pi/Axway"
expect -exact "/home/pi/Axway"
send -- "\r"
expect -exact "\r
Upgrade information\r
If you have an Activator 5.10.1 or later installed you can upgrade to\r
Activator 6.1 using the data from the Activator installation.\r
\r
Upgrade from Activator 5.x or later?\r
Yes \[y\], No \[n, Enter\]\r
"
send -- "n\r"
expect -exact "n\r
Select option: \r
Previous screen \[p\], Next screen \[n, Enter\], Cancel \[c\]\r
"
send -- "\r"
expect -exact "\r
Shared directory location\r
Enter the location of the common directory to store documents and other\r
files.\r
\r
NOTE: Potentially large amounts of data will be stored here. This directory\r
will contain the common directory which will be created if does not already\r
exist.\r
\r
\[/opt/axway/activator/common\]\r
"
send -- "/opt/axway/activator/common"
expect -exact "/opt/axway/activator/common"
send -- "\r"
expect -exact "\r
Select option: \r
Previous screen \[p\], Next screen \[n, Enter\], Cancel \[c\]\r
"
send -- "n\r"
expect -exact "n\r
License file location\r
Enter the location of the license file:\r
\[\]\r
"
send -- "/home/pi/license.xml"
expect -exact "/home/pi/license.xml"
send -- "\r"
expect -exact "\r
Select option: \r
Previous screen \[p\], Next screen \[n, Enter\], Cancel \[c\]\r
"
send -- "\r"
expect -exact "\r
Start install tasks\r
\r
All information required for the installation has been collected.\r
\r
Click Next to start installation of the Axway Activator.\r
\r
\[Enter\]\r
"
send -- "\r"
expect eof
EOF

chown pi:pi /home/pi/autoInstall_Activator6.1.sh
chmod 777 /home/pi/autoInstall_Activator6.1.sh
sudo /home/pi/autoInstall_Activator6.1.sh &
wait
sudo rm /home/pi/autoInstall_Activator6.1.sh
sudo rm /home/pi/Activator_6.1_Install_linux-x86-64_BN6.sh

# Retirando o comentário do autoStartAbastece.sh
sudo sed -i '/#edi/ s/#edi/edi/g'  /bin/autoStartAbastece.sh